version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./client:/app/
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001
  api:
    build:
      context: ./api
    ports:
      - "5000:5001"
      - "9229:9229"
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - API_PORT=5001
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
  db:
    build:
      context: ./db
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=password
    - DATABASE_URL=postgres://postgres:password@db:5432/postgres
volumes:
  db-volume:
